version: "3"
services: 
  client:
    build: ./client/
    container_name: todo-client
    ports:
      - '4200:4200'
    volumes:
      - .:/opt/client
    command: ng serve --open
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
  todo-server:
    build: ./server/
    container_name: todo-server
    image: todo-server
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=todo
      - DATABASE_USER=springuser
      - DATABASE_PASSWORD=Todo@1234
      - DATABASE_NAME=todos
      - DATABASE_PORT=3306